API/urls.py
from django import views
from django.urls import path, include
from . import serializer
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from . import views
from rest_framework.authtoken.views import obtain_auth_token
app_name='api'

urlpatterns = [
       path('token/', obtain_auth_token, name="api_token_auth"),
       path('empenhos/', views.add_empenho.as_view()),       
]

fiscalizacao/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name='obra'

urlpatterns = [
    path('get_empresa/', views.get_empresa, name='get_empresa' ),    
    path('get_notas/', views.get_notas, name='get_notas' ),    
    path('get_notas_arquivadas/', views.get_notas_arquivadas, name='get_notas_arquivadas' ),    
    path('teste/', views.teste, name='teste' ),

    path('', views.index, name='index' ),

    path('login/', views.login_view, name='login' ),
    path('logout/', views.logout_view, name='logout' ),

    path('cadastrar-obra/', views.cadastrar_obra, name='cadastrar' ),
    path('get-obras/', views.get_obras, name='get_obras' ),
    path('get-empenho/', views.get_empenhos, name='get_empenhos' ),
    
    path('dados-obras/<valor_busca>', views.listar_obras, name='visualizar' ),
    path('dados-obras/v/<id>', views.visualizar_obra, name='visualizar_obra' ),
    
    path('dados-obras/v/<id>/editar', views.editar_obra, name='editar_obra' ),

    path('dados-obras/v/<id>/fotos', views.visualizar_fotos_obra, name='visualizar_fotos_obra' ),
    path('dados-obras/v/<id>/fotos/<url>', views.visualizar_foto_obra, name='visualizar_foto_obra' ),
    path('dados-obras/v/<id>/fotos/<url>/arquivar', views.arquivar_foto_obra, name='arquivar_foto_obra' ),
    
    path('dados-obras/v/<id>/notas', views.visualizar_notas, name='visualizar_notas' ),
    path('dados-obras/v/<id>/notas_arquivadas', views.visualizar_notas_arquivadas, name='visualizar_notas_arquivadas' ),
    path('dados-obras/v/<id>/notas/editar-empenho/<id_empenho>', views.editar_empenho, name='editar_empenho' ),
    path('dados-obras/v/<id>/notas/editar-empenho/<id_empenho>/substituir', views.substituir_empenho, name='substituir_empenho' ),
    path('dados-obras/v/<id>/notas/arquivar-empenho/<id_empenho>', views.arquivar_empenho, name='arquivar_empenho' ),
    path('dados-obras/v/<id>/notas/editar-nota/<id_nota>', views.editar_nota, name='editar_nota' ),
    path('dados-obras/v/<id>/notas/arquivar-nota/<id_nota>', views.arquivar_nota, name='arquivar_nota' ),
    path('dados-obras/v/<contrato_id>/notas/cad_empenho', views.cadastrar_empenho, name='cadastrar_empenho' ),

    path('cadastrar-empresa/', views.cadastrar_empresa, name='cadastrar_empresa' ),
    path('editar-empresa/<id>', views.editar_empresa, name='editar_empresa' ),
    path('listar-empresa/', views.listar_empresa, name='listar_empresa' ),
    path('listar-empresa/v/<id>', views.visualizar_empresa, name='visualizar_empresa' ),    
    path('listar-empresa/h', views.historico_empresa, name='historico_empresa' ),
    path('listar-empresa/h/a/<id>', views.historico_empresa_acoes, name='historico_empresa_acoes' ),

    path('cadastrar-fiscal/', views.cadastrar_fiscal, name='cadastrar_fiscal' ),
    path('listar-fiscais/', views.listar_fiscais, name='listar_fiscais' ),
    path('editar-fiscal/<id>', views.editar_fiscal, name='editar_fiscal' ),


    # path('ver-obra/', views.fiscalizar_obra, name='buscar' ),
    # path('ver-obra/<valor_busca>', views.fiscalizar_obra, name='visualizar' ),
    path('gerar-qr-code/<obra_id>', views.gerar_qr_code, name='gerar_qrcode' ),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('qr-code/', include('qr_code.urls', namespace="qr_code")),
    path('', include('fiscalizacao.urls')),
    path('api/', include('API.urls')),
    path('django-admin/', admin.site.urls),    
]

fiscalizacao/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User


class Status(models.Model):
    nome=models.CharField(max_length=50)
    
    def __str__(self):
        return '%s' % (self.nome)

class Nota_Empenho(models.Model):
    
    # PERIODO_CHOICES=[
    #     ('a', 'Ano'),
    #     ('m', 'Mês'),
    #     ('s', 'Semana'),        
    #     ('d', 'Dia'),        
    # ]
    TIPO_CHOICES=[
        ('in', 'Inicial'),
        ('sd', 'Substituido'),
        ('st', 'Substituto'),        
        ('co', 'Complementar'),        
    ]

    tipo_empenho=models.CharField(max_length=2, choices=TIPO_CHOICES, default='in', verbose_name='Tipo de empenho')    
    substituto=models.IntegerField(verbose_name='Substituto', blank=True, default=0)
    substituindo=models.IntegerField(verbose_name='Substituindo', blank=True, default=0)
    n_nota=models.IntegerField(verbose_name='N. da nota de empenho', unique=True)
    data=models.DateField(verbose_name='Data de expedição do empenho')
    valor=models.CharField(max_length=20,verbose_name='Valor do empenho(R$)')
    # tipo_periodo=models.CharField(max_length=1, choices=PERIODO_CHOICES, default='a', verbose_name='Tipo de período do empenho')
    # periodo=models.CharField( max_length=5,verbose_name='Período do empenho')
    url=models.CharField(max_length=300, default='#', verbose_name='Link da nota do empenho')
    ativo=models.BooleanField(default=False)
    abatido=models.BooleanField(default=False)
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 


    def __str__(self):
        return '%s' % (self.n_nota)

class Nota_Fiscal(models.Model):
    
    # PERIODO_CHOICES=[
    #     ('a', 'Ano'),
    #     ('m', 'Mês'),
    #     ('s', 'Semana'),        
    #     ('d', 'Dia'),        
    # ]
    
    empenho=models.ForeignKey(Nota_Empenho, on_delete=models.CASCADE)
    n_nota=models.CharField(max_length=100 ,verbose_name='N. da nota fiscal')
    data=models.DateField(verbose_name='Data de expedição fiscal')
    valor=models.CharField(max_length=20,verbose_name='Valor da nota (R$)')
    # tipo_periodo=models.CharField(max_length=1, choices=PERIODO_CHOICES, default='a', verbose_name='Tipo de Período')
    periodo_inicial=models.DateField(verbose_name='Período inicial da medição')
    periodo_final=models.DateField(verbose_name='Período final da medição')
    url=models.CharField(max_length=300, default='#', verbose_name='Link da nota')
    ativo=models.BooleanField(default=False, null=True)
    obs=models.TextField(verbose_name='Observações')
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 


    def __str__(self):
        return '%s - %s' % (self.id, self.n_nota)

class Nota_Fiscal_Arquivada(models.Model):    
    nota=models.ForeignKey(Nota_Fiscal, on_delete=models.CASCADE)
    dt_arquivado=models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em') 
    
class Empresa(models.Model):
    nome=models.CharField(max_length=150, verbose_name='Nome da empresa')
    cnpj=models.CharField(max_length=14, verbose_name='CNPJ', unique=True)
    cadastrado_por=models.ForeignKey(User, on_delete=models.PROTECT)
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 

    def __str__(self):
        return '%s' % (self.nome)

class Fiscal(models.Model):
    nome=models.CharField(max_length=150, verbose_name='Nome do Fiscal')
    crea=models.CharField(max_length=150, verbose_name='CREA')
    matricula=models.CharField(max_length=150, verbose_name='Matrícula')
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 

    def __str__(self):
        return '%s' % (self.nome)

class Obra(models.Model):        

    n_processo_adm=models.CharField(max_length=50, default='', blank=True, verbose_name='Número do Processo Administrativo') 
    objeto_da_obra=models.CharField(max_length=150, verbose_name='Objeto da obra')
    populacao_atendida=models.CharField(max_length=150, verbose_name='População atendida')
    valor_previsto=models.CharField(max_length=20, verbose_name='Valor previsto do contrato (R$)')
    n_processo_pagamento=models.CharField(max_length=50, default='', blank=True, verbose_name='Número do Processo de Pagamento') 
    status=models.ForeignKey(Status, on_delete=models.PROTECT, verbose_name='Situação')    
    fiscal=models.ForeignKey(Fiscal,on_delete=models.PROTECT, verbose_name='Fiscal responsável')
    fiscal_substituto=models.ForeignKey(Fiscal,on_delete=models.PROTECT, verbose_name='Fiscal substituto', related_name='substituto')
    engenheiro=models.CharField(max_length=250, verbose_name='Nome do engenheiro responsável', default='')
    justificativa=models.TextField(verbose_name='Justificativa')
    data_conclusao=models.DateField(verbose_name='Data prevista de conclusão', blank=True, null=True)
    cadastrado_por=models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 
    #latitude e longitude
    
    def __str__(self):
        return '%s %s' % (self.id, self.objeto_da_obra)

class Contrato(models.Model): 

    obra=models.ForeignKey(Obra, on_delete=models.CASCADE)   
    empresa=models.ForeignKey(Empresa, on_delete=models.PROTECT, verbose_name='Empresa contratada')
    nota_empenho=models.ManyToManyField(Nota_Empenho, blank=True)
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 

    def __str__(self):
        return '%s - %s' % (self.id, self.nota_empenho)

# class Aditivos(models.Model):

#     contrato=models.ForeignKey(Contrato, on_delete=models.CASCADE)
#     nota_fiscal=models.ForeignKey(Nota_Fiscal, on_delete=models.PROTECT)    
    
class Obra_Fiscal(models.Model):

    STATUS_CHOICES=[
        ('r', 'Responsável'),
        ('s', 'Suplente'),
        ('f', 'Férias'),
    ]
    obra=models.ForeignKey(Obra, on_delete=models.CASCADE)
    fiscal=models.ForeignKey(Fiscal, on_delete=models.CASCADE)
    status=models.CharField(max_length=1, choices=STATUS_CHOICES)

class Fotos(models.Model):   
    obra=models.ForeignKey(Obra, on_delete=models.CASCADE) 
    url=models.CharField(max_length=300)

    def __str__(self):
        return '%s' % (self.url)

class Aditivo(models.Model):
    prazo=models.BooleanField()
    valor=models.BooleanField()
    id_empenho=models.CharField(max_length=50)

class Log(models.Model):

    TABELAS=[                
        ('stu', 'Status de Obra'),
        ('nte', 'Nota de Empenho'),
        ('emp', 'Empresa'),
        ('ntf', 'Nota Fiscal'),
        ('fis', 'Fiscal'),        
        ('obr', 'Obra'),
        ('con', 'Contrato'),
        ('adi', 'Aditivos'),
    ]    
    TIPOS=[
        ('c', 'Criado'),        
        ('u', 'Atualizado'),
        ('a', 'Arquivado'),
        ('d', 'Deletado'),

    ]
    tabela=models.CharField(max_length=3, blank=False, choices=TABELAS)
    ref=models.IntegerField(blank=True, default=0)
    tipo=models.CharField(max_length=1, blank=False, choices=TIPOS)
    acao=models.CharField(max_length=300, blank=False)
    dt_inclusao = models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão') 
    user=models.CharField(max_length=150)
    ipv4=models.CharField(max_length=15, verbose_name='IP')    
    # ipv6=CharField(max_length=16)    
    def __str__(self):
        return '%s - %s - %s' % (self.tabela, self.acao, self.user)

fiscalizacao/forms.py
from .models import Contrato, Empresa, Fiscal, Nota_Empenho, Nota_Fiscal, Obra
from .validations import validate_CNPJ

from django import forms
from django.forms import ModelForm, ValidationError

class Form_Obras(ModelForm): 

    class Meta:
        model = Obra
        widgets = {'cadastrado_por': forms.HiddenInput(),                   
                   'valor_previsto': forms.TextInput(attrs={'onkeydown':"maskValor(this)", 'onload':"maskValor(this)"}),
                   'status': forms.Select(attrs={'class':'form-select mb-3'}),
                   'fiscal': forms.Select(attrs={'class':'form-select mb-3'}),
                   'fiscal_substituto': forms.Select(attrs={'class':'form-select mb-3'}),}
        exclude = ['dt_inclusao']
    
    def clean_valor_previsto(self):                        
        valor=self.cleaned_data["valor_previsto"]
        valor = valor.replace('.', '')
        valor = valor.replace(',', '')        
        return valor

class Form_Fiscal(ModelForm): 
    
    class Meta:
        model = Fiscal
        widgets = {'cadastrado_por': forms.HiddenInput()}
        exclude = ['dt_inclusao']

class Form_Empresa(ModelForm): 

    cnpj=forms.CharField(label="CNPJ", max_length=18, required=True,  widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icnpj)"}))
    class Meta:
        model = Empresa
        widgets = {'cadastrado_por': forms.HiddenInput()}
        exclude = ['dt_inclusao']

    def clean_cnpj(self):                
        cnpj = validate_CNPJ(self.cleaned_data["cnpj"])
        cnpj = cnpj.replace('.', '')
        cnpj = cnpj.replace('-', '')
        return cnpj


class Form_Empenho(ModelForm):     
    class Meta:
        model = Nota_Empenho
        widgets = {'valor': forms.TextInput(attrs={'onkeydown':"maskValor(this)", 'onload':"maskValor(this)"}),
                   'tipo_periodo': forms.Select(attrs={'class':'form-select mb-3'}),
                   'tipo_empenho': forms.HiddenInput(),
                   'substituindo': forms.HiddenInput()
                   }
        exclude = ['ativo', 'dt_inclusao', 'abatido', 'substituto']        

    def clean_valor(self):                        
        valor=self.cleaned_data["valor"]
        valor = valor.replace('.', '')
        valor = valor.replace(',', '')        
        return valor

class Form_Empenho_Desabilitado(ModelForm): 

    class Meta:
        model = Nota_Empenho
        widgets = {'n_nota': forms.TextInput(attrs={'disabled':'true'}),
                    'data': forms.DateInput(attrs={'disabled':'true'}),
                   'valor': forms.TextInput(attrs={'onkeydown':"maskValor(this)", 'disabled':'true', 'onload':"maskValor(this)"}),
                   'tipo_periodo': forms.Select(attrs={'class':'form-select mb-3', 'disabled':'true'}),
                   'periodo': forms.TextInput(attrs={'disabled':'true'}),
                   'url': forms.TextInput(attrs={'disabled':'true'}),}        
        exclude = ['ativo', 'dt_inclusao', 'tipo_empenho', 'abatido', 'substituto', 'substituindo']

    def clean_valor(self):                        
        valor=self.cleaned_data["valor"]
        valor = valor.replace('.', '')
        valor = valor.replace(',', '')        
        return valor

class Form_Nota(ModelForm): 

    class Meta:
        model = Nota_Fiscal
        widgets = {'valor': forms.TextInput(attrs={'onkeydown':"maskValor(this)"}),
                   'tipo_periodo': forms.Select(attrs={'class':'form-select mb-3'}),}        
        exclude = ['dt_inclusao', 'ativo']

    def clean_valor(self):                        
        valor=self.cleaned_data["valor"]
        valor = valor.replace('.', '')
        valor = valor.replace(',', '')        
        return valor


class Form_Contrato(ModelForm): 

    class Meta:
        model = Contrato        
        exclude = ['dt_inclusao']

fiscalizacao/templates/fiscalizacao/cadastrar_empresa.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load widget_tweaks %} 
{% block main %}
{% if success %}
<div class="row px-4 py-2">
    <div class="col bg-success d-flex">
        <p class="text-white m-auto fw-bolder py-1">{{success}}</p>
    </div>
</div>
{%endif%}
<div class="row">    
    <div class="col container p-5">
        <div class="d-flex">
            <h1 class="text-uppercase">Cadastrar empresa</h1>            
            <span class="ms-auto"><a class="btn btn-primary" href="{% url 'obra:listar_empresa' %}">
                <i class="fas fa-list-ol me-2"></i>
                Listar Empresas</a></span>
        </div>
        <form method="post" class="form col-5">            
            {% csrf_token %}
            <br>
            <div id="contrato">
                {% for f in form %}
                {% if f.name != 'cadastrado_por' %}
                <label for="">{{f.label}}:</label>
                {% endif %}
                {{f|add_class:'form-control mb-3'}}            
                {% endfor %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">CONFIRMAR</button>
                {% endbuttons %}
            </div>         
        </form>
    </div>
</div>
<script>
    function icnpj(v){
        v=v.replace(/\D/g,"")                    //Remove tudo o que nao e digito
        v=v.replace(/(\d{2})(\d)/,"$1.$2")       //Coloca um ponto entre o segundo e terceiro digitos
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o quinto e o sexto digitos
        v=v.replace(/(\d{3})(\d)/,"$1/$2")       //Coloca um ponto entre o quinto e o sexto digitos
        v=v.replace(/(\d{4})(\d)/,"$1-$2")       //Coloca um ponto entre o quinto e o sexto digitos
        // v=v.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, "$1.$2.$3/$4-$5")
        return v
    }
    function mascara(o,f){
        v_obj=o
        v_fun=f
        setTimeout("execmascara()",1)
    }            
    function execmascara(){
        v_obj.value=v_fun(v_obj.value)
    }    
</script>
{% endblock %}

fiscalizacao/templates/fiscalizacao/editar_empenho.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load widget_tweaks %} 
{% block main %}
{% if success %}
<div class="row px-4 py-2">
    <div class="col bg-success d-flex">
        <p class="text-white m-auto fw-bolder py-1">{{success}}</p>
    </div>
</div>
{%endif%}
<div class="row">    
    <div class="col container p-5">
        <div class="d-flex">
            <h1 class="text-uppercase">Editar empenho</h1>            
            <span class="ms-auto">
                <a class="btn btn-danger" href="{% url 'obra:arquivar_empenho' id id_empenho %}">
                    <i class="fas fa-archive me-2"></i>Arquivar
                </a>
                <a class="btn btn-primary" href="{% url 'obra:visualizar_notas' id %}">
                    <i class="far fa-arrow-alt-circle-left me-2"></i>
                    Voltar
                </a>
            </span>
        </div>
        <div class="row">
            <form method="post" class="form col-5">            
                {% csrf_token %}
                <br>
                <div id="contrato">
                {% for f_nota in form %}
                {% if f_nota.label == 'Data de expedição do empenho' %}
                <label for="">{{f_nota.label}}:</label>
                {{f_nota|add_class:'form-control mb-3'|attr:'type:date'}}  
                {% else %}
                <label for="">{{f_nota.label}}:</label>
                {{f_nota|add_class:'form-control mb-3'|attr:'type:text'|attr:'autocomplete:off'}}            
                {% endif %}
                {% endfor %}       
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">                            
                            CONFIRMAR
                        </button>
                    {% endbuttons %}
                </div>         
            </form>
            <div class="col d-flex pt-5">
                <div class="mx-auto">
                    <a href="{% url 'obra:substituir_empenho' id id_empenho %}" class="btn btn-warning p-4">
                        <i class="fas fa-file-export me-2"></i>
                        Substituir Empenho
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
<script>
    function icnpj(v){
        v=v.replace(/\D/g,"")                    //Remove tudo o que nao e digito
        v=v.replace(/(\d{2})(\d)/,"$1.$2")       //Coloca um ponto entre o segundo e terceiro digitos
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o quinto e o sexto digitos
        v=v.replace(/(\d{3})(\d)/,"$1/$2")       //Coloca um ponto entre o quinto e o sexto digitos
        v=v.replace(/(\d{4})(\d)/,"$1-$2")       //Coloca um ponto entre o quinto e o sexto digitos
        // v=v.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, "$1.$2.$3/$4-$5")
        return v
    }
    function mascara(o,f){
        v_obj=o
        v_fun=f
        setTimeout("execmascara()",1)
    }            
    function execmascara(){
        v_obj.value=v_fun(v_obj.value)
    }
    function maskValor(input){    
        $(input).mask('#.##0.000,00', {reverse: true});
    }
    window.onload=()=>{
        let valor = document.querySelector("#id_valor");
        maskValor(valor);
    }
</script>
{% endblock %}

fiscalizacao/templates/fiscalizacao/listar_itens_obra.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load widget_tweaks %}  
{% block main %}

<div class="row">    
    <div class="col container p-5">
        <div class="row">
            <div class="col">
                <h1>DADOS DA OBRA</h1>
            </div>
            <div class="col d-flex" style="position: relative;">   
                {% if request.user.is_authenticated %}
                <a class="btn btn-primary ms-auto me-2 my-auto" href="{% url 'obra:gerar_qrcode' obra.id %}">
                    QR Code <i class="fas fa-qrcode ms-2"></i>
                </a>             
                <a class="btn btn-primary me-2 my-auto" href="{% url 'obra:editar_obra' obra.id %}">
                    Editar <i class="fas fa-pencil-alt ms-2"></i>
                </a>       
                <a class="btn btn-primary my-auto" href="{% url 'obra:visualizar' obra.id %}">
                    <i class="far fa-arrow-alt-circle-left me-2"></i>
                    Voltar
                </a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col pt-4" id="searchResult">   
                <div class="p-3">
                    <div class="mb-2" style="background-color: #d6e7f8;">
                        <div class="py-3 px-3">                        
                            <div class="d-flex ps-4">
                                <span class="my-auto"><b>id: </b>{{obra.id}}</span>
                                <span class="ms-auto">                                    
                                    <a href="{% url 'obra:visualizar_fotos_obra' obra.id %}" class="btn btn-outline-success me-2">Fotos</a>
                                    <a href="{% url 'obra:visualizar_notas' obra.id %}" class="btn btn-outline-success">Notas</a>                                    
                                </span>
                            </div>
                        </div>
                    </div>                
                    <table class="table table-light table-striped mt-0">                                   
                        <tbody>                        
                            <tr>                   
                                <!-- <th class="text-end">id:</th>          
                                <td>{{obra.id}}</td>   -->
                                <td colspan="2" class="px-3">
                                    <b>Empresa:</b><br>
                                    <span>{{obra.empresa.nome}}</span>
                                </td>         
                                <td colspan="2" class="">
                                    <b>Objeto da Obra:</b><br>
                                    <span>{{obra.obra.objeto_da_obra}}</span>    
                                </td>
                                <td colspan="2">
                                    <b>Valor previsto:</b><br>
                                    R$ <span id="valorp">{{obra.obra.valor_previsto}}</span>
                                </td>
                                <td colspan="2">
                                    <b>Engenheiro responsável:</b><br>
                                    <span>{{obra.obra.engenheiro}}</span>
                                </td>           
                            </tr>    
                            <tr>                   
                                <td colspan="0" class="px-3">
                                    <b>CNPJ da empresa:</b><br>                      
                                    <span id="cnpj">{{obra.empresa.cnpj}}</span>
                                </td>         
                                <td colspan="1">
                                    <b>População atendida:</b><br>
                                    <span>{{obra.obra.populacao_atendida}}</span>
                                </td>
                                <td colspan="2" class="px-3">
                                    <b>Fiscal Responsável:</b><br>                      
                                    <span>{{obra.obra.fiscal}}</span>
                                </td>
                                <td colspan="2" class="px-3">
                                    <b>Fiscal Substituto:</b><br>                      
                                    <span>{{obra.obra.fiscal_substituto}}</span>
                                </td>   
                                <td colspan="2" class="px-3 row">
                                    <b>Status:</b> <br>                     
                                    <span class='{% if obra.obra.status.nome == "Em andamento" %}bg-info{% elif obra.obra.status.nome == "Paralisada" %}bg-warning{% elif obra.obra.status.nome == "Finalizada" %}bg-success{% endif %} text-white text-center bolder p-1 w-100' >{{obra.obra.status}}</span>
                                </td>  
                                 
                            </tr>   
                            <tr>
                                <td colspan="8" class="px-3">
                                    <b>Data prevista de conclusão:</b><br>
                                    <span>{{obra.obra.data_conclusao}}</span>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="8" class="p-3">
                                    <b>Justificativa:</b>
                                    <p>
                                        {{obra.obra.justificativa}}
                                    </p>
                                </td>
                            </tr>
                            {% if request.user.is_authenticated %}
                            <tr>
                                <td colspan="2">
                                    <b class="ms-2 me-3">Nº processo administrativo:</b> <span>{{obra.obra.n_processo_adm}}</span>
                                </td>
                                <td colspan="4" >
                                    <b>Nº processo de pagamento:</b> <span class="text-capitalize ms-3">{{obra.obra.n_processo_pagamento}}</span>
                                </td>
                                <td colspan="2" ></td>
                         
                                     

                            </tr>
                            <tr>
                                <td colspan="2">
                                    <b class="ms-2">Data de Inclusão:</b> <span>{{obra.obra.dt_inclusao}}</span>
                                </td>
                                <td colspan="4" >
                                    <b>Cadastrado por:</b> <span class="text-capitalize ms-3">{{obra.obra.cadastrado_por.first_name}}</span>
                                </td>                            
                                <td></td>
                                <td></td>                               

                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>      
    </div>
</div>
<style>
.form-control:disabled, .form-control[readonly]{               
font-weight: bold;
}
label{
font-weight: bold;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
<script>
function search(input){    
getObra(input.value)
}

function getObra(value){
var url = '/get-obras/';  // get the url of the `load_cities` view        
$.ajax({ 
    url: url,
    data: {
        'nome': value,
    },
    success: function(data) {                               
        $("#searchResult").html(data);
    }
});                
};

$("#valorn").mask('#.##0.000,00', {reverse: true});
$("#valorp").mask('#.##0.000,00', {reverse: true});
$("#cnpj").mask("99.999.999/9999-99");
</script>
{% endblock %}